- id: '1711100044845'
  alias: Assist Google speaker status
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.boxa_din_bucatarie
    to: idle
    id: kitchen display on
  - platform: state
    entity_id:
    - media_player.boxa_din_bucatarie
    to: 'off'
    id: kitchen display off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - kitchen display on
      sequence:
      - service: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.relu_voice_google_speaker_status
    - conditions:
      - condition: trigger
        id:
        - kitchen display off
      sequence:
      - service: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.relu_voice_google_speaker_status
    - conditions: []
      sequence: []
  mode: single
- id: '1711101868158'
  alias: Assist Change Assistants
  description: ''
  trigger:
  - platform: conversation
    command:
    - Aș vrea să vorbesc cu Jarvis
    - Aș vrea să vorbesc cu Gearvis
    - Speak  romanian
    id: JarvisRo
  - platform: conversation
    command:
    - Aș vrea să vorbesc în engleză
    id: JarvisEn
  - platform: conversation
    command:
    - Aș vrea să vorbesc cu șeila
    - Aș vrea să vorbesc cu che la
    id: SheilaRo
  - platform: conversation
    command:
    - Aș vrea să vorbesc cu Roumi
    - Aș vrea să vorbesc cu roaming
    - Aș vrea să vorbesc cu romi
    id: RoomieRo
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - JarvisRo
      sequence:
      - service: select.select_option
        metadata: {}
        data:
          option: Jarvis
        target:
          entity_id: select.relu_voice_assistant_select
      - service: select.select_option
        metadata: {}
        data:
          option: Jarvis
        target:
          entity_id: select.relu_voice_pipeline_assist
      - service: conversation.process
        metadata: {}
        data:
          agent_id: homeassistant
          text: ok
    - conditions:
      - condition: trigger
        id:
        - JarvisEn
      sequence:
      - service: select.select_option
        metadata: {}
        data:
          option: JarvisEn
        target:
          entity_id: select.relu_voice_assistant_select
      - service: select.select_option
        metadata: {}
        data:
          option: JarvisEn
        target:
          entity_id: select.relu_voice_pipeline_assist
    - conditions:
      - condition: trigger
        id:
        - SheilaRo
      sequence:
      - service: select.select_option
        metadata: {}
        data:
          option: Sheila
        target:
          entity_id: select.relu_voice_assistant_select
      - service: select.select_option
        metadata: {}
        data:
          option: Sheila
        target:
          entity_id: select.relu_voice_pipeline_assist
    - conditions:
      - condition: trigger
        id:
        - RoomieRo
      sequence:
      - service: select.select_option
        metadata: {}
        data:
          option: Roomie
        target:
          entity_id: select.relu_voice_assistant_select
      - service: select.select_option
        metadata: {}
        data:
          option: Roomie
        target:
          entity_id: select.relu_voice_pipeline_assist
  mode: single
