- id: '1707375574862'
  alias: Assist random responses
  description: Execute random_responses shell command when a wake word engine is activated
  trigger:
  - platform: state
    entity_id:
    - wake_word.openwakeword
    - wake_word.porcupine
    - wake_word.porcupine1
    - wake_word.snowboy
  condition: []
  action:
  - service: shell_command.random_responses
    data: {}
  mode: single
